appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: oPr8J0Ax0QSovEyY+cst4EIDrvprjA9JyUwBJCfq3zKQFpGBRQW+wqpNbAy0bI/LN+ybi9Dh3dA7fVIcDc2ycypbKSX4z4uBLvjB33VA5XscW1w98S5Dnr+0xmb0bPTwNxltt31jdYu8lk/YLTYL9a7iubsv+DxPZzmTp3TY4v4eJ+XCHIPXamlZLMUTqzw2V+aEdX9z7qBsYK4LsUiHXDraXlz4hWEBz7B1lB5GPtXO9fB3N0sLlF0uNKcS5NgmiJhFrgqzMFhkcBg8+C0TxE4DAbmEAV9Ij2qNpZDiInbIkhExKUPFXU5vPgKiaszXzLjwz0loK9DTp8NqTFNHlu8zzrB4dsjbvpfzS8NdxrTTfhH2HbIwyZrgweFsEISYKFLjNoRr0lb9jKGtsocW7lzJEg3eKwQ/vrdOXmeDpXxZYWrBLy2hiygEyJ2ufYxvHru5aQDeFavB7TpEmRFXqbzchBum1C8OdQOyWyhUTjTuIT9zsloSQc7gHBn2XBRYgSu7T+G+vtEhqCo4jt7W2s1C9wvFGfxnwaxeVwESPgLp49/L8jpfBUtLyEdTBY14qT4w/3lbWfaoPbA0C859RaUSDEHxR9ryQfYOU9EkoAHcRVt2pUFt2JoAdA+lT56n0cpPVxavdnKabo0l6a3aDZ3bxkl/aXLEPXB6Gwut6/A=}
